services:
  db:
    image: postgres:17
    restart: always
    container_name: fate-template-db
    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: fate
      POSTGRES_PASSWORD: echo
